version: '3.9'

services:
     
  db:
    build: ./db
    env_file:
      - ./db/.env
    networks:
      - dummy
    volumes:
      - couch:/opt/couchbase/var/

networks:
  dummy:
  
volumes:
  couch:


