// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quiz_Service.Data;

#nullable disable

namespace be.Migrations
{
    [DbContext(typeof(QuizContext))]
    [Migration("20230426194332_FixSumModel")]
    partial class FixSumModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Quiz_Service.Models.Program_Matching_Criteria", b =>
                {
                    b.Property<string>("ProgramId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Accounting")
                        .HasColumnType("float");

                    b.Property<double>("Adventure_or_action")
                        .HasColumnType("float");

                    b.Property<double>("Animal_care_or_animal_training")
                        .HasColumnType("float");

                    b.Property<double>("Arabic")
                        .HasColumnType("float");

                    b.Property<double>("Art")
                        .HasColumnType("float");

                    b.Property<double>("Art_or_drawing_or_paint_or_sculpture")
                        .HasColumnType("float");

                    b.Property<double>("Assist_others_to_resolve_conflict_situations")
                        .HasColumnType("float");

                    b.Property<double>("Astronomy_or_weather_forecasting")
                        .HasColumnType("float");

                    b.Property<double>("Athletic_activities")
                        .HasColumnType("float");

                    b.Property<double>("Aviation")
                        .HasColumnType("float");

                    b.Property<double>("Avoid_majors_lasting_more_than_4_years")
                        .HasColumnType("float");

                    b.Property<double>("Avoid_working_with_hazardous_situations_or_materials")
                        .HasColumnType("float");

                    b.Property<double>("Biology")
                        .HasColumnType("float");

                    b.Property<double>("Building_or_machining_or_repair_work")
                        .HasColumnType("float");

                    b.Property<double>("Business")
                        .HasColumnType("float");

                    b.Property<double>("Chemistry")
                        .HasColumnType("float");

                    b.Property<double>("Combine_work_with_learning")
                        .HasColumnType("float");

                    b.Property<double>("Computer_IT")
                        .HasColumnType("float");

                    b.Property<double>("Computer_graphics")
                        .HasColumnType("float");

                    b.Property<double>("Computer_programming")
                        .HasColumnType("float");

                    b.Property<double>("Computer_social_networking")
                        .HasColumnType("float");

                    b.Property<double>("Cooking")
                        .HasColumnType("float");

                    b.Property<double>("Dance")
                        .HasColumnType("float");

                    b.Property<double>("Debate_or_public_speaking")
                        .HasColumnType("float");

                    b.Property<double>("Drama_or_lighting_or_scenery_or_theatre")
                        .HasColumnType("float");

                    b.Property<double>("Electronics_or_radio_or_sound_systems_or_television")
                        .HasColumnType("float");

                    b.Property<double>("Engage_in_high_stress_and_perhaps_risky_undertakings")
                        .HasColumnType("float");

                    b.Property<double>("Engage_in_religious_activities")
                        .HasColumnType("float");

                    b.Property<double>("Engage_in_scientific_problem_solving")
                        .HasColumnType("float");

                    b.Property<double>("Engage_in_social_issues_and_actions")
                        .HasColumnType("float");

                    b.Property<double>("English")
                        .HasColumnType("float");

                    b.Property<double>("Entrepreneurship_or_Jr_Achievement")
                        .HasColumnType("float");

                    b.Property<double>("Ethnic_and_regional_cultures_or_history")
                        .HasColumnType("float");

                    b.Property<double>("Exercise_your_creativity")
                        .HasColumnType("float");

                    b.Property<double>("Exert_power_and_authority")
                        .HasColumnType("float");

                    b.Property<double>("Gardening")
                        .HasColumnType("float");

                    b.Property<double>("Healthcare_related_services")
                        .HasColumnType("float");

                    b.Property<double>("Helping_People_Solve_Problems")
                        .HasColumnType("float");

                    b.Property<double>("History")
                        .HasColumnType("float");

                    b.Property<double>("Language_club_orethnic_heritage_")
                        .HasColumnType("float");

                    b.Property<double>("Limit_choices_to_careers_with_an_above_average_salary")
                        .HasColumnType("float");

                    b.Property<double>("Maintain_hard_working_disciplined_study_skills")
                        .HasColumnType("float");

                    b.Property<double>("Math")
                        .HasColumnType("float");

                    b.Property<double>("Math_team")
                        .HasColumnType("float");

                    b.Property<double>("Mentoring_or_Future_Teachers")
                        .HasColumnType("float");

                    b.Property<double>("Music")
                        .HasColumnType("float");

                    b.Property<double>("Music_band_or_chorus_or_performance")
                        .HasColumnType("float");

                    b.Property<double>("Nutrition_or_exercise_or_physical_fitness")
                        .HasColumnType("float");

                    b.Property<double>("Outdoor_activities_or_camping_or_hiking")
                        .HasColumnType("float");

                    b.Property<double>("Participate_in_sports_and_physically_demanding_activities")
                        .HasColumnType("float");

                    b.Property<double>("Philosophy")
                        .HasColumnType("float");

                    b.Property<double>("Photography_or_video")
                        .HasColumnType("float");

                    b.Property<double>("Physical_Education")
                        .HasColumnType("float");

                    b.Property<double>("Physics")
                        .HasColumnType("float");

                    b.Property<double>("Problem_solving_or_strategy")
                        .HasColumnType("float");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Provide_nursing_andor_healthcare_related_services")
                        .HasColumnType("float");

                    b.Property<double>("Psychology")
                        .HasColumnType("float");

                    b.Property<double>("Public_dramatic_or_musical_performance")
                        .HasColumnType("float");

                    b.Property<double>("ROTC_or_other_military_activities")
                        .HasColumnType("float");

                    b.Property<double>("Religious_training_or_spirituality")
                        .HasColumnType("float");

                    b.Property<double>("Rely_on_and_trust_in_your_peers_camaraderie")
                        .HasColumnType("float");

                    b.Property<double>("Rely_on_mental_images")
                        .HasColumnType("float");

                    b.Property<double>("Science_or_engineering")
                        .HasColumnType("float");

                    b.Property<double>("Social_Studies_Government_Geography")
                        .HasColumnType("float");

                    b.Property<double>("Social_work_service_activities")
                        .HasColumnType("float");

                    b.Property<double>("Speak_to_and_facilitate_groups_of_people_at_work")
                        .HasColumnType("float");

                    b.Property<double>("Stay_involved_in_current_events")
                        .HasColumnType("float");

                    b.Property<double>("Student_government_or_leadership")
                        .HasColumnType("float");

                    b.Property<double>("Study_a_major_that_has_a_clear_connection_to_a_career")
                        .HasColumnType("float");

                    b.Property<double>("Study_different_peoples_and_cultures")
                        .HasColumnType("float");

                    b.Property<double>("Sum")
                        .HasColumnType("float");

                    b.Property<double>("Teach_children_young_people_or_adults")
                        .HasColumnType("float");

                    b.Property<double>("Technology_clubs")
                        .HasColumnType("float");

                    b.Property<double>("Travel")
                        .HasColumnType("float");

                    b.Property<double>("Use_your_manual_and_mechanical_skills")
                        .HasColumnType("float");

                    b.Property<double>("Value_leadership_training_and_experiences")
                        .HasColumnType("float");

                    b.Property<double>("Work_in_a_business_environment")
                        .HasColumnType("float");

                    b.Property<double>("Work_on_self_initiated_projects")
                        .HasColumnType("float");

                    b.Property<double>("Working_Alone")
                        .HasColumnType("float");

                    b.Property<double>("Working_Outdoors")
                        .HasColumnType("float");

                    b.Property<double>("Working_With_Children_or_Young_People")
                        .HasColumnType("float");

                    b.Property<double>("Working_With_Immediately_Practical_Things")
                        .HasColumnType("float");

                    b.Property<double>("Working_with_Detailed_Logical_Structure")
                        .HasColumnType("float");

                    b.Property<double>("Working_with_Organizations_and_Groups")
                        .HasColumnType("float");

                    b.Property<double>("Writing_or_reading_or_yearbook_or_newspaper")
                        .HasColumnType("float");

                    b.Property<double>("third_language")
                        .HasColumnType("float");

                    b.HasKey("ProgramId");

                    b.ToTable("QuizDB");
                });
#pragma warning restore 612, 618
        }
    }
}
